### ISSUE TITLE
[BUG] removing video from queue also removes current download

### ISSUE THREAD

**Issue by JimZiii** [deniscerri/ytdlnis#210]
**Describe the bug**
When i have a download running and have one or more downloads in the queue, if i remove any of the videos in the queue it will remove the one i asked to remove and the current download at the same tim and, the next queued download will start.

**To Reproduce**
Start 2 or more downloads, go to queue tab and delete one of them and the current download will also get cancelled.

**Expected behavior**
To remove a video from the queue and only have that video get removed, not the one already downloading

**Screenshots / Video Recording**
If you can't reproduce it let me know and I'll post a recording

**(please complete the following information):**
 - Android Version: 13
 - App Version: 1.6.3 (latest)
 - Other Device Information: also running latest yt-dlp, but i don't think that's relevant to this issue

**Additional context**
As a workaround it's luckily pretty easy to scroll back to the cancelled tab and start it again and it'll start where it left off

**Comment by deniscerri** [comment]
Was able to reproduce it. Will fix

**Comment by deniscerri** [comment]
it has been fixed

**Comment by JimZiii** [comment]
This still happens if i select multiple objects in the queue and delete them, at least when i use "select all".

I also have a request. There's currently no way to pause or stop a download other than to cancel it, which works the exact same way, so I'd suggest renaming the action and the tab to something more fitting and easier for new users to understand.

There's also no way to cancel or stop multiple queued downloads at the same time, when selecting multiple objects in the queue, you're only able to delete them completely.


If you'd prefer them on a new ticket let me know and I'll open one

**Comment by deniscerri** [comment]
its fixed in the latest beta
