### ISSUE TITLE
[BUG] Fly-Out Menu appears lower than usual on a Tablet

### ISSUE THREAD

**Issue by PandoraPandorita** [deniscerri/ytdlnis#91]
**Describe the bug**
When sharing a video to download, opening a link directly in the app, or even clicking an already downloaded video, the fly-out (I think that's what this menu is called at least) appears nearly hidden away when using landscape mode on a tablet. Examples below. 

**To Reproduce**

- Share a video link to the app in landscape mode on a tablet
- Notice how the menu appears nearly hidden in the navigation menu. 

**Expected behavior**
The menu should be displayed at the correct height on the screen. 

**Screenshots / Video Recording**

Sharing to download:
![Screenshot_20230416-174258](https://user-images.githubusercontent.com/79670265/232351172-19a4d4e2-7173-475c-a2cc-6c0e97063470.png)

Clicking an already downloaded file:
![Screenshot_20230416-174241](https://user-images.githubusercontent.com/79670265/232351225-6daf5cb5-6999-468e-8ead-b9a4bb63d1ab.png)

Direct download:
![Screenshot_20230416-180037](https://user-images.githubusercontent.com/79670265/232351255-cacf7eef-75b8-4bf8-bac8-8e49fda9cf81.png)

What should appear by default:
![Screenshot_20230416-180948](https://user-images.githubusercontent.com/79670265/232351500-4393d7c9-a2c3-461d-8034-f83518cb26a2.png)

**(please complete the following information):**
 - Android Version: 10
 - App Version: 1.5.0
 - Other Device Information: Alcatel Joy Tab 2, still stuck on Android 10.

**Additional context**
There could be a better tablet UI, and since Android 12L and 13 were focused on that, it would be nice for those to be added, however, that's another github issue.

**Comment by deniscerri** [comment]
Noted

**Comment by deniscerri** [comment]
Fixed in latest commits. Will close this when the release drops

**Comment by PandoraPandorita** [comment]
The issue still persists, but only with the downloads.

Downloaded items:
![Screenshot_20230429-065100](https://user-images.githubusercontent.com/79670265/235303499-b1eb4ac4-8df5-4ed8-9e28-ccb79be05a9d.png)

Download menu:
![Screenshot_20230429-065132](https://user-images.githubusercontent.com/79670265/235303523-0aa1647f-23d5-474b-9703-a7db0a498f17.png)

Probably just a me with a crappy tablet issue, but I guess reporting it ain't bad.
Also, ignore my downloads, I've been using the app quite a bit.

**Comment by soymadip** [comment]
> The issue still persists, but only with the downloads.
> 
> Downloaded items:
> ![Screenshot_20230429-065100](https://user-images.githubusercontent.com/79670265/235303499-b1eb4ac4-8df5-4ed8-9e28-ccb79be05a9d.png)
> 
> Download menu:
> ![Screenshot_20230429-065132](https://user-images.githubusercontent.com/79670265/235303523-0aa1647f-23d5-474b-9703-a7db0a498f17.png)
> 
> Probably just a me with a crappy tablet issue, but I guess reporting it ain't bad.
> Also, ignore my downloads, I've been using the app quite a bit. 

I guess that commit is not released yet (i am not sure though)

**Comment by deniscerri** [comment]
MF Doom nice.
Also ill give it another look

**Comment by deniscerri** [comment]
I think i figured it out. The reason for this is because im cutting the download card size cuz i didnt want it to fill the whole screen. But since tablets are in landscape its eating way more space than planned, thats why it barely shows up.

From now on the card will show up full size, or shorter depending on its size.

Current:
![image](https://user-images.githubusercontent.com/64997243/235305355-030f4f46-ec73-44d6-9e55-f0908367349b.png)

Now:
![image](https://user-images.githubusercontent.com/64997243/235305374-b933be18-0bb7-4d97-887b-b9ac48f0d35b.png)
