### ISSUE TITLE
[Feature] An option to prefer non-drc audio

### ISSUE THREAD

**Issue by MagicalDrizzle** [deniscerri/ytdlnis#925]
### Describe the feature

A switch to toggle whether -drc audio should be preferred over regular audio.

### Reason for adding

Currently, ytdlnis prefers -drc youtube audio, which I believe is at odds with the current yt-dlp default. If you want non-drc audio, you have to use a custom template or override the format (e.g to 251) in settings. I think it would be nice to have a switch to toggle whether you want drc audio by default or not.

### Example(s)

<img width="1080" height="558" alt="Image" src="https://github.com/user-attachments/assets/112cac62-3ab6-4883-93fb-5dd830963c24" />

<img width="1079" height="585" alt="Image" src="https://github.com/user-attachments/assets/51274a62-f44a-441e-a8b8-78f026c5abb5" />

**Comment by deniscerri** [comment]
@MagicalDrizzle  try this build

https://github.com/deniscerri/ytdlnis/actions/runs/17892101702/artifacts/4065541896
the setting is in processing settings, audio section in the end

i couldnt test it cuz i cant find drc formats but it should work in theory lol

**Comment by MagicalDrizzle** [comment]
this is really weird, now no matter what that drc switch is set to, it will always choose *non*-drc audio
(also reverting to the original apk just crash the app now)

**Comment by deniscerri** [comment]
@MagicalDrizzle send me some links that have drc audio please, so i can properly test

**Comment by teddysulaimanGL** [comment]
~~It's very likely because she doesn't wait for the data fetching to be completed~~

Whoops, yeah, I think I can reprod

**Comment by MagicalDrizzle** [comment]
@deniscerri 
https://youtu.be/ZS3O0OOn0a0
https://youtu.be/w_oSxqT-wqE
https://youtu.be/E-bU8dHwSFo
@teddysulaimanGL Well I think five minutes for one single video metadata fetching is plenty but maybe that's not enough
Oddly the order in the format list is correct, drc is below normal audio
but the actual format that is chosen is still drc

<img width="1079" height="912" alt="Image" src="https://github.com/user-attachments/assets/f7bc0fba-263c-4110-b0d6-48c64d81837b" />

<img width="1080" height="1717" alt="Image" src="https://github.com/user-attachments/assets/541aff86-8e86-43c2-8be7-9990426f8b21" />

**Comment by teddysulaimanGL** [comment]
Though, is there any particular reason to choose a toggle over the preferred format ID(s)? 🤔

**Comment by MagicalDrizzle** [comment]
Because the specific format ID is not always available
if I put 251 in to prefer it to 251-drc, what if there's only 140 and I want to prefer it over 140-drc?

**Comment by teddysulaimanGL** [comment]
Separate them with a slash to set the fallback. 251-drc/140-drc

**Comment by MagicalDrizzle** [comment]
It's just easier to say "I don't want drc" than to add a slash for every format that could possibly have drc lol
or I mean it's easy to create a template and exclude it with -f
but an universal toggle just seems cleaner

**Comment by teddysulaimanGL** [comment]
Preferred ID applies to -f aka format selection right before the command building even before data fetching, so… it's not correct to think that the GUI Command download type is the last resort to do this.
However, this change is quite understandable for convenience

**Comment by MagicalDrizzle** [comment]
Yeah I mean "convenience" is the purpose of the whole damn app lol
otherwise you can just install termux and do pip install yt-dlp on it

**Comment by teddysulaimanGL** [comment]
Ye, don't worry. I'll discuss it with Denis ASAP

**Comment by deniscerri** [comment]
Try this
https://github.com/deniscerri/ytdlnis/actions/runs/17956005412/artifacts/4086281414

**Comment by MagicalDrizzle** [comment]
Still the same issue as the last apk unfortunately...Now it's stuck at preferring non-drc audio regardless of what the toggle is set to

**Comment by deniscerri** [comment]
@MagicalDrizzle maybe u reinstalled the old apk twice lol
i tried it again and it works as expected. Tested on first url u gave me

**Comment by MagicalDrizzle** [comment]
if you can't reproduce it then i'm not sure lol, I downloaded and installed the apk again just to make sure, it's the second one
if it works well for you then feel free to close this issue!

**Comment by deniscerri** [comment]
@MagicalDrizzle if it doesnt work for you, then the feature doesnt work lol.
Send me an url u tried
Also send me full screenshot of your processing settings please

**Comment by deniscerri** [comment]
@MagicalDrizzle yo, does the feature work now? lol, idk

**Comment by MagicalDrizzle** [comment]
same inverted behavior
now the switch doesn't change anything, non-drc will always be preferred over drc

**Comment by deniscerri** [comment]
@MagicalDrizzle I made some changes so that the toggle always not prefers drc audio. It should work now i guess. Wait for the CI build and test it out

**Comment by deniscerri** [comment]
@MagicalDrizzle please respond 😞

**Comment by MagicalDrizzle** [comment]
hmm, it's still the same for me
no matter what the toggle is set to, it still always chooses non-drc
I have a suggestion to rename/change the toggle maybe? to "Prefer DRC audio"
<img width="1080" height="2105" alt="Image" src="https://github.com/user-attachments/assets/10a37d01-71e2-448c-98b6-45b8ae61c9ff" />

**Comment by deniscerri** [comment]
I mean you tried the ci build
Not the release

**Comment by MagicalDrizzle** [comment]
Yeah, I just downloaded the latest CI build https://github.com/deniscerri/ytdlnis/actions/runs/20146396762

**Comment by deniscerri** [comment]
Ok I'll rename it

**Comment by deniscerri** [comment]
@MagicalDrizzle yo, wait for the ci build. Let me know
I reversed them. Forgot about this issue for a bit lol
